### ISSUE TITLE
NuxtServerError unable to verify the first certificate

### ISSUE THREAD

**Issue by tiptronic** [bovas85/nuxt-headless#3] opened 2019-01-14 15:52 UTC
trying to load `http://localhost:3000` brings up an certificate error:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80752/51123578-a9e4b600-181c-11e9-91bf-a166bd2204d0.png">

**Comment by bovas85** [comment] 2019-01-14 15:57
what command are you using to run the app?

Make sure you follow the readme, and can I ask you to please add reproduction steps? 

Also please make sure you don't open a new issue for each comment :)

**Comment by bovas85** [comment] 2019-01-14 15:58
Also make sure you change the config to point to your wordpress installation

**Comment by tiptronic** [comment] 2019-01-14 15:59
- I have a local Wordpress install (using MAMP PRO) on:
`https://ghsnuxt.test/`  (which runs fine).

- I copied the `nuxt-headless` into a folder of the WP installation (ghsnuxt.test/nuxt-headless/)
- and entered `ghsnuxt.test,localhost` into 'Allowed domains'

-I modified the assets/config.js:

```
"use strict";

// configure this file following the example below.
// these are the rest api endpoints and your wordpress url
const Config = {
  appTitle: "Nuxt Headless",
  appTitleShort: "Nuxt-headless",
  appDescription: "Nuxt Headless with Wordpress REST API",
  appThemeColor: "#ffffff ",
  appBgColor: "#00172c ",
  appIcon: "assets/app-icon.png",
  wpDomain: "https://ghsnuxt.test/wp-json",
  client: "https://ghsnuxt.test",
  url: "https://ghsnuxt.test",
  api: {
    homePage: "/wp/v2/pages/[page_id]",
    // this url will hit an endpoint for contact form 7 plugin
    postFormContact: "/contact-form-7/v1/contact-forms/{form_id}/feedback"
  }
};

export default Config;

```

then `yarn dev'

**Comment by bovas85** [comment] 2019-01-14 16:05
The idea for this is to point to an online WP installation. I haven't tested locally but I assume there would be no issue here.

It seems though that the certificate you have on your local is self signed and might not work with chrome? 

I'd try adding a CORS rule or proxy, but the issue is on wp-end rather than the repo itself

**Comment by tiptronic** [comment] 2019-01-14 16:06
I will put the WP-installation on a server tonight - and let you know how that worked

**Comment by bovas85** [comment] 2019-01-14 16:17
sure, I remember using this locally, but it seems that your mamp is complaining about a missing cert on your WP installation. I'd try adding a CORS plugin on chrome to allow all.

Closing as this is not related to the repo, but feel free to add questions or your solution here and keep me posted :)

**Closed by bovas85** 2019-01-14 16:17 UTC
Labels: question

**Comment by paramula** [comment] 2021-11-06 04:40
[https://stackoverflow.com/questions/55440261/nuxt-js-problem-with-server-side-api-call-with-https](url)
